((nil . ((cider-refresh-before-fn . "reloaded.repl/suspend")
         (cider-refresh-after-fn  . "reloaded.repl/resume")
         (cider-clojure-cli-global-options . "-A:dev:datomic-free")
         (cider-preferred-build-tool . clojure-cli)
         (cider-repl-display-help-banner . nil))))
