version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1
  clojure: lambdaisland/clojure@0.0.1

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - kaocha/execute:
                aliases: "dev:datomic-free"
                args: "unit --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
            - kaocha/upload_codecov:
                flags: unit

jobs:
  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.0"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.0"}}]

workflows:
  kaocha_test:
    jobs:
      - java-11-clojure-1_10
      - java-8-clojure-1_10
